name: Spring Boot CI - Build JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build, run tests, and generate coverage
        run: mvn verify

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ms1-jar
          path: target/ms1-0.0.1.jar

      - name: SonarCloud Scan
        run: mvn sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t app-ms1:$TAG .
          docker tag app-ms1:$TAG 723626972680.dkr.ecr.ap-south-1.amazonaws.com/app-ms1:$TAG

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 723626972680.dkr.ecr.ap-south-1.amazonaws.com/app-ms1:$TAG
